{
 "title": "UT performance metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Service",
    "query": "label_values(count_ms, service)"
   },
   { "name": "Implementation", "query": "label_values(count_ms, impl)" }
  ]
 },
 "panels": [
  {
   "title": "Exec / wait time per method (milliseconds)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max_over_time({__name__=\"time_x_max\", m!=\"*\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{name}} / {{m}} (execute)"
    },
    {
     "expr": "max_over_time({__name__=\"time_w_max\", m!=\"*\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{name}} / {{m}} (wait)"
    }
   ]
  },
  {
   "title": "Throughput (operations per second)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({__name__=\"count_ms\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{service}} / {{name}} (send)"
    },
    {
     "expr": "avg_over_time({__name__=\"count_mr\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{service}} / {{name}} (receive)"
    }
   ]
  },
  {
   "title": "Traffic (bytes per second)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({__name__=\"count_bs\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{service}} / {{name}} (send)"
    },
    {
     "expr": "avg_over_time({__name__=\"count_br\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{service}} / {{name}} (receive)"
    }
   ]
  },
  {
   "title": "Concurrency (active operations)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max_over_time({__name__=\"count_ax_max\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{service}} / {{name}} (execute)"
    },
    {
     "expr": "max_over_time({__name__=\"count_aw_max\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{service}} / {{name}} (dispatch)"
    },
    {
     "expr": "max_over_time({__name__=\"count_as_max\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{service}} / {{name}} (send)"
    },
    {
     "expr": "max_over_time({__name__=\"count_ar_max\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}[$__interval])",
     "legendFormat": "{{service}} / {{name}} (receive)"
    },
    {
     "expr": "{__name__=\"count_ae_max\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}",
     "legendFormat": "{{service}} / {{name}} (encode)"
    },
    {
     "expr": "{__name__=\"count_ad_max\", service =~ \"[[Service]]\", impl =~\"[[Implementation]]\"}",
     "legendFormat": "{{service}} / {{name}} (decode)"
    }
   ]
  }
 ]
}